const modeToggle=document.getElementById('modeToggle'),menuToggle=document.getElementById('menuToggle'),primaryNav=document.getElementById('primaryNav'),todayLabel=document.getElementById('todayLabel'),resetChecks=document.getElementById('resetChecks');
function setTheme(dark){document.body.classList.toggle('dark-mode',dark);if(modeToggle)modeToggle.textContent=dark?'☾':'☀';localStorage.setItem('gea-theme',dark?'dark':'light')}
const savedTheme=localStorage.getItem('gea-theme');setTheme(savedTheme?savedTheme==='dark':window.matchMedia('(prefers-color-scheme: dark)').matches);modeToggle?.addEventListener('click',()=>setTheme(!document.body.classList.contains('dark-mode')));
menuToggle?.addEventListener('click',()=>{const open=primaryNav.classList.toggle('open');menuToggle.setAttribute('aria-expanded',String(open))});primaryNav?.addEventListener('click',e=>{if(e.target.closest('a')){primaryNav.classList.remove('open');menuToggle?.setAttribute('aria-expanded','false')}});
// 편집된 브리핑 날짜를 유지합니다. 매일 자동 업데이트가 index.html의 날짜를 갱신합니다.
document.querySelectorAll('.filter-chip').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.filter-chip').forEach(item=>item.classList.remove('active'));button.classList.add('active');const filter=button.dataset.filter;document.querySelectorAll('[data-topic]').forEach(card=>{card.hidden=filter!=='all'&&card.dataset.topic!==filter})}));
const checkboxes=document.querySelectorAll('[data-check]');checkboxes.forEach(box=>{box.checked=localStorage.getItem(`gea-check-${box.dataset.check}`)==='true';box.addEventListener('change',()=>localStorage.setItem(`gea-check-${box.dataset.check}`,String(box.checked)))});resetChecks?.addEventListener('click',()=>checkboxes.forEach(box=>{box.checked=false;localStorage.removeItem(`gea-check-${box.dataset.check}`)}));


// --- Crypto Intelligence Dashboard ---
const cryptoStatus=document.getElementById('cryptoDataStatus'),cryptoUpdatedAt=document.getElementById('cryptoUpdatedAt');
const usdFormatter=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2});
const krwFormatter=new Intl.NumberFormat('ko-KR',{style:'currency',currency:'KRW',maximumFractionDigits:0});
function compactUsd(value){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:2}).format(value)}
function renderChange(element,value){if(!element||!Number.isFinite(value))return;element.textContent=`24시간 ${value>=0?'+':''}${value.toFixed(2)}%`;element.classList.toggle('up',value>=0);element.classList.toggle('down',value<0)}
function renderSparkline(id,prices){const svg=document.querySelector(`[data-chart-id="${id}"]`);const line=svg?.querySelector('polyline');if(!svg||!line||!Array.isArray(prices)||prices.length<2)return;const values=prices.map(point=>Array.isArray(point)?Number(point[1]):Number(point)).filter(Number.isFinite);if(values.length<2)return;const min=Math.min(...values),max=Math.max(...values),range=max-min||1,pad=3,width=120-pad*2,height=48-pad*2;const points=values.map((value,index)=>`${(pad+(index/(values.length-1))*width).toFixed(2)},${(pad+((max-value)/range)*height).toFixed(2)}`).join(' ');line.setAttribute('points',points);const up=values.at(-1)>=values[0];svg.classList.toggle('up',up);svg.classList.toggle('down',!up);svg.classList.remove('loading');svg.setAttribute('aria-label',`${id} 최근 24시간 가격 그래프, ${up?'상승':'하락'} 흐름`)}
function renderCryptoMarket(data,mode='saved'){
  if(!data?.assets?.length)return;
  data.assets.forEach(asset=>{const card=document.querySelector(`[data-crypto-id="${asset.id}"]`);if(!card)return;const price=card.querySelector('.crypto-price'),krw=card.querySelector('.crypto-krw'),change=card.querySelector('.crypto-change'),volume=card.querySelector('.crypto-volume'),cap=card.querySelector('.crypto-cap'),rank=card.querySelector('.crypto-rank');if(price)price.textContent=usdFormatter.format(asset.priceUsd);if(krw)krw.textContent=krwFormatter.format(asset.priceKrw);renderChange(change,asset.change24h);if(volume)volume.textContent=compactUsd(asset.volume24hUsd);if(cap)cap.textContent=compactUsd(asset.marketCapUsd);if(rank)rank.textContent=`시총 #${asset.rank}`});
  if(data.charts24h)Object.entries(data.charts24h).forEach(([id,prices])=>renderSparkline(id,prices));
  const market=data.market||{};const totalCap=document.getElementById('cryptoTotalCap'),totalVolume=document.getElementById('cryptoTotalVolume'),dominance=document.getElementById('cryptoBtcDominance'),marketChange=document.getElementById('cryptoMarketChange');if(totalCap)totalCap.textContent=compactUsd(market.totalMarketCapUsd);if(totalVolume)totalVolume.textContent=compactUsd(market.totalVolume24hUsd);if(dominance)dominance.textContent=`${market.btcDominance?.toFixed(1)}%`;renderChange(marketChange,market.marketCapChange24h);
  if(cryptoStatus){cryptoStatus.textContent=mode==='live'?'실시간 시장 데이터':'마지막 저장 데이터';cryptoStatus.className=`status-dot ${mode}`}
  if(cryptoUpdatedAt){const observed=new Date(data.observedAt);cryptoUpdatedAt.textContent=`${new Intl.DateTimeFormat('ko-KR',{dateStyle:'medium',timeStyle:'short'}).format(observed)} 기준`}
}
async function loadSavedCrypto(){try{const response=await fetch('data/crypto-snapshot-latest.json',{cache:'no-store'});if(!response.ok)throw new Error('saved snapshot unavailable');const saved=await response.json();renderCryptoMarket(saved,'saved');return saved}catch(error){console.warn('저장된 암호화폐 데이터 로딩 실패',error);return null}}
async function loadLiveCrypto(){try{const [usdResponse,krwResponse,globalResponse]=await Promise.all([fetch('https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&ids=bitcoin,ethereum,ripple&price_change_percentage=24h'),fetch('https://api.coingecko.com/api/v3/coins/markets?vs_currency=krw&ids=bitcoin,ethereum,ripple&price_change_percentage=24h'),fetch('https://api.coingecko.com/api/v3/global')]);if(!usdResponse.ok||!krwResponse.ok||!globalResponse.ok)throw new Error('live API unavailable');const [usd,krw,global]=await Promise.all([usdResponse.json(),krwResponse.json(),globalResponse.json()]);const live={observedAt:new Date().toISOString(),source:'CoinGecko',assets:usd.map(item=>{const local=krw.find(value=>value.id===item.id);return{id:item.id,symbol:item.symbol.toUpperCase(),name:item.name,priceUsd:item.current_price,priceKrw:local?.current_price,change24h:item.price_change_percentage_24h,volume24hUsd:item.total_volume,marketCapUsd:item.market_cap,rank:item.market_cap_rank}}),market:{totalMarketCapUsd:global.data.total_market_cap.usd,totalVolume24hUsd:global.data.total_volume.usd,btcDominance:global.data.market_cap_percentage.btc,marketCapChange24h:global.data.market_cap_change_percentage_24h_usd}};renderCryptoMarket(live,'live')}catch(error){console.warn('실시간 암호화폐 데이터 로딩 실패, 저장 데이터 유지',error);if(cryptoStatus&&!cryptoStatus.classList.contains('saved')){cryptoStatus.textContent='데이터 일시 지연'}}}
async function loadLiveCharts(){const ids=['bitcoin','ethereum','ripple'];document.querySelectorAll('.crypto-sparkline').forEach(svg=>svg.classList.add('loading'));try{const responses=await Promise.all(ids.map(id=>fetch(`https://api.coingecko.com/api/v3/coins/${id}/market_chart?vs_currency=usd&days=1`)));if(responses.some(response=>!response.ok))throw new Error('chart API unavailable');const payloads=await Promise.all(responses.map(response=>response.json()));payloads.forEach((payload,index)=>renderSparkline(ids[index],payload.prices))}catch(error){console.warn('24시간 그래프 실시간 로딩 실패, 저장 그래프 유지',error);document.querySelectorAll('.crypto-sparkline').forEach(svg=>svg.classList.remove('loading'))}}
if(document.getElementById('cryptoGrid')){loadSavedCrypto().finally(()=>Promise.allSettled([loadLiveCrypto(),loadLiveCharts()]))}
